services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 54321:5432
    # set shared memory limit when using docker compose
    shm_size: 256mb
    volumes:
      - ./pg-data:/var/lib/postgresql
      - ./pg-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: pgmaster
      POSTGRES_PASSWORD: XXXXX
      TZ: "Asia/Tokyo"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8989:8080

